### ISSUE TITLE
🚀 [feature] FCM 세팅

### ISSUE THREAD

**Issue by CYY1007** [Team-Shaka/Briefing-Backend#156]
# 🤖 기능 개요

## FCM 세팅

FCM을 이용한 푸쉬 알림 (단, 이벤트 기반이 아닌 스케줄러 기반) 구현을 위한 기본적인 세팅을 합니다.

### 데이터베이스 테이블 설계

우선적으로 알림을 저장 할 테이블 설계가 필요하며

추후 알림을 터치 시 적절한 페이지로의 이동을 위해 알림 테이블에서 외래키로 참조를 해야 합니다.
그러나 데이터베이스는 다형성이 없기 때문에 런 타임(sql을 읽어들이는 시점)에서 어떤 대상에 대한 알림인지
파악하기가 불가능 하기 때문에 테이블 설계에서 이를 가능하게 해야 합니다.

방안은 크게 세 가지 입니다.

1. 슈퍼 타입, 서브 타입의 사용
2. 모든 알림마다 테이블 분리
3. 대상이 되는 칼럼을 nullable한 외래키로 두고, dtype으로 구분

1번 같은 경우 데이터에 대한 무결성등이 가장 강력히 보장이 되지만 join 연산이 크게 늘어납니다.
2번과 3번은 비슷한 방식이나 2번은 매번 칼럼이 추가되어야 하고, 3번은 매번 테이블이 추가가 되어야 합니다.

join 연산을 크게 늘리지 않으면서도 관리가 좀 더 용이한 2번 방식을 차용하려고 합니다.

### fegin 클라이언트

외부 API를 fegin 클라이언트를 사용해 호출 할 예정입니다.

## ✅ Todo
- [x] 엔티티 매핑
- [ ] fegin 클라이언트 세팅

**Comment by swa07016** [comment]
저도 2번 방식에 동의합니다.

1번 방식 상속을 사용했을 경우, 부모 자식간 강한 결합으로 정책 변화에 오히려 대응하기 어려울 것 같고,
3번 방식을 사용했을 경우 각 테이블별로 특화된 필드들에 대해 null값이 많이 생길 수 있다고 생각합니다.

결론적으로 알림별로 테이블을 분리해서 깔끔하게 관리하는 2번 방식이 좋아보입니다.
