### ISSUE TITLE
🔨[refactor] Facade 도입 & 클래스 의존관계 개선

### ISSUE THREAD

**Issue by swa07016** [Team-Shaka/Briefing-Backend#161]
# 🔨 리팩토링이 필요한 부분 
기존 설계를 점검해보았습니다. 여러 문제점이 있습니다.
### 기존 설계
**클래스 의존관계**
![image](https://github.com/Team-Shaka/Briefing-Backend/assets/53550707/7ca194e7-b784-4472-8875-15df1f85bb82)

**DTO & Entity 간의 변환**
<img src="https://github.com/Team-Shaka/Briefing-Backend/assets/53550707/2faae466-5e08-41d3-9ce8-b2f927e3a9d7" width="50%"/>

**문제점**
1. Controller에서 필요한 여러 서비스를 의존해서 여러 엔티티를 받고있습니다. (Controller가 여러 Service를 알고 있어야하며, 이렇게 설계되어 있을 경우 추후 Controller가 비즈니스 로직까지 수행해버릴 수 있습니다.)
2. Entity가 Controller 계층까지 노출되고 있습니다.
3. Service(CommandService)는 필요한 여러 리포지토리를 의존해서 비즈니스 로직을 구성하고 있습니다.
4. DTO 와 Entity 간의 변환을 위해 Controller, Service 두 곳에서 Converter를 의존하고 있습니다.
5. CommandService는 여러 관심사를 가집니다. (Service의 재사용성이 떨어집니다.)
    - 예시) BriefingCommandService의 create 메소드는 Briefing 엔티티의 생성, Article 엔티티의 생성, BriefingArticle 엔티티의 생성 총 3가지 일을 수행하고 있습니다.

### 개선된 설계
아래와 같이 리팩토링할 예정입니다.
**클래스 의존관계**
![image](https://github.com/Team-Shaka/Briefing-Backend/assets/53550707/ac399df1-e739-41b5-987b-23919734abae)
**DTO & Entity 간의 변환**
<img src="https://github.com/Team-Shaka/Briefing-Backend/assets/53550707/b86b8e4e-90ed-4d7b-96fe-c69df478342a" width="60%"/>

**계층별 역할**
1. Controller) 
    - 클라이언트로 부터 요청을 받고 응답을 줍니다.
    - 클라이언트 요청 데이터의 유효성을 검사합니다.
2. Facade)
    - 비즈니스 로직을 수행합니다.
    - Converter를 의존하여 DTO ↔ Entity간 변환을 수행해줍니다.
    - 트랜잭션을 관리합니다.
3. Service)
    - XQueryService) X엔티티의 Read를 담당합니다.
    - XCommandSerivce) X엔티티의 Create, Update, Delete를 담당합니다.

이런식으로 관심사를 분리하여, Service계층은 해당하는 엔티티의 CRUD만 담당하고, Controller는 타 로직(ex. DTO ↔ Entity간 변환)을 알 필요없이 요청/응답에만 집중할 수 있도록 할 예정입니다.

**Comment by CYY1007** [comment]
더 좋은 아키텍처 제안 좋습니다! 반반 나눠서 퍼사드 패턴에 대한 연습을 해봐도 좋을 것 같습니다.

**Comment by swa07016** [comment]
> 더 좋은 아키텍처 제안 좋습니다! 반반 나눠서 퍼사드 패턴에 대한 연습을 해봐도 좋을 것 같습니다.

넵! 우선 제가 Briefing 도메인쪽 리팩토링해보고 리뷰 받고 다음에 Member나 다른 도메인쪽 해주시면 좋을 것 같아요!
